# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    schema: classpath:db/schema.sql
    #    data: classpath:db/data.sql
    url: jdbc:mysql://data_mysql:3306/company_frame?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 5
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
  redis:
    host: data_redis
    port: 6379
    timeout: PT10S
    lettuce:
      pool:
        max-active: 100
        max-idle: 30
        max-wait: PT10S
        min-idle: 1
    password:

jwt:
  accessTokenExpireTime: PT2H
  issuer: hanyunpeng0521.github.io
  refreshTokenExpireAppTime: P30D
  refreshTokenExpireTime: PT8H
  secretKey: 78944878877848fg)

